/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-10-18 07:55:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mvc.bean.StudentBean;
import java.util.ArrayList;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Home Page</title>\n");
      out.write("<style>\n");
      out.write("* {\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".column {\n");
      out.write("  float: left;\n");
      out.write("  width: 33.33%;\n");
      out.write("  padding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Clearfix (clear floats) */\n");
      out.write(".row::after {\n");
      out.write("  content: \"\";\n");
      out.write("  clear: both;\n");
      out.write("  display: table;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */\n");
      out.write("@media screen and (max-width: 500px) {\n");
      out.write("  .column {\n");
      out.write("    width: 100%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=button], input[type=submit], input[type=reset] {\n");
      out.write("  background-color: #4CAF50;\n");
      out.write("  border: none;\n");
      out.write("  color: white;\n");
      out.write("  padding: 12px 25px;\n");
      out.write("  text-decoration: none;\n");
      out.write("  margin: 4px 2px;\n");
      out.write("  cursor: pointer;\n");
      out.write("  font-weight:bold;\n");
      out.write("  font-size:13px;\n");
      out.write("}\n");
      out.write("input[type=text] {\n");
      out.write("  width: 70%;\n");
      out.write("  padding: 12px 20px;\n");
      out.write("  margin: 8px 0;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("  border: 1px solid #555;\n");
      out.write("  outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=text]:focus {\n");
      out.write("  background-color: lightblue;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<center>\n");
      out.write("\t\t<h2 style=\"color:purple; font-weight:bold\">Home Page</h2>\n");
      out.write("\t\t<h3 style=\"color:blue; font-weight:bold\">Welcome</h3>\n");
      out.write("\t</center>\n");
      out.write("\t<p style=\"text-align:center;\"><img src=\"images/icons/portal.jpg\" height=\"350px\" width=\"700px\"></p>\n");
      out.write("\t<div class=\"row\">\n");
      out.write("  <div class=\"column\">\n");
      out.write("    <img src=\"images/icons/student_info.jpg\" height=\"180px\" width=\"200px\">\n");
      out.write("    <form name=\"form\" action=\"StudentServlet\" method=\"post\">\n");
      out.write("\t\n");
      out.write("\t<h3 style=\"color:SlateBlue; font-weight:bold\">Get Student Info</h3><input type=\"text\" name=\"id\" placeholder=\"Enter student id\"/> \n");
      out.write("\t<br><input type=\"submit\" value=\"Submit\"></input><input type=\"reset\" value=\"Reset\"></input>\n");
      out.write("\t</form>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"column\">\n");
      out.write("    <img src=\"images/icons/course_info.jpg\" height=\"180px\" width=\"200px\">\n");
      out.write("    <form name=\"form\" action=\"CourseServlet\" method=\"post\">\n");
      out.write("\n");
      out.write("\t\t<h3 style=\"color:SlateBlue; font-weight:bold\">Get Course Info</h3><input type=\"text\" name=\"id\" placeholder=\"Enter student id\"/> \n");
      out.write("\t\t<br><input type=\"submit\" value=\"Submit\"></input><input type=\"reset\" value=\"Reset\"></input>\n");
      out.write("\t</form>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"column\">\n");
      out.write("    <img src=\"images/icons/advisor.jpg\" height=\"180px\" width=\"200px\">\n");
      out.write("    <form name=\"form\" action=\"AdvisorServlet\" method=\"post\">\n");
      out.write("\n");
      out.write("\t\t<h3 style=\"color:SlateBlue; font-weight:bold\">Get Advisor Info</h3> <input type=\"text\" name=\"id\" placeholder=\"Enter student id\"/> \n");
      out.write("\t\t<br><input type=\"submit\" value=\"Submit\"></input><input type=\"reset\" value=\"Reset\"></input>\n");
      out.write("\t</form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\t<!-- Refer to the video to understand how this works -->\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
